apiVersion: v1
kind: Service
metadata:
  labels:
    app: nebula-metad
  name: nebula-metad
  namespace: {{ .Values.namespace }}
spec:
  publishNotReadyAddresses: true
  ports:
  - name: thrift
    port: {{ .Values.port.metad.thriftPort }}
  - name: raft
    port: {{ .Values.port.metad.raftPort }}
  - name: http
    port: {{ .Values.port.metad.httpPort }}
  - name: http2
    port: {{ .Values.port.metad.http2Port }}
  selector:
    app: nebula-metad
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nebula-storaged
  name: nebula-storaged
  namespace: {{ .Values.namespace }}
spec:
  publishNotReadyAddresses: true
  ports:
  - name: thrift
    port: {{ .Values.port.storaged.thriftPort }}
  - name: raft
    port: {{ .Values.port.storaged.raftPort }}
  - name: http
    port: {{ .Values.port.storaged.httpPort }}
  - name: http2
    port: {{ .Values.port.storaged.http2Port }}
  selector:
    app: nebula-storaged
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nebula-graphd
  name: nebula-graphd
  namespace: {{ .Values.namespace }}
spec:
  publishNotReadyAddresses: true
  type: NodePort
  ports:
  - name: thrift
    port: {{ .Values.port.graphd.thriftPort }}
  - name: http
    port: {{ .Values.port.graphd.httpPort }}
  - name: http2
    port: {{ .Values.port.graphd.http2Port }}
  selector:
    app: nebula-graphd
---
{{- $root := . -}}
{{ range $index := until (atoi (quote .Values.replication.metad.replicas) | default 3) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nebula-metad-{{ $index }}
  name: nebula-metad-{{ $index }}
  namespace: {{ $root.Values.namespace }}
spec:
  publishNotReadyAddresses: true
  type: NodePort
  ports:
    - name: thrift
      port: {{ $root.Values.port.metad.thriftPort }}
    - name: raft
      port: {{ $root.Values.port.metad.raftPort }}
    - name: http
      port: {{ $root.Values.port.metad.httpPort }}
    - name: http2
      port: {{ $root.Values.port.metad.http2Port }}
  selector:
    statefulset.kubernetes.io/pod-name: nebula-metad-{{ $index }}
---
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nebula-graph-studio
  name: nebula-graph-studio
  namespace: {{ .Values.namespace }}
spec:
  publishNotReadyAddresses: true
  type: NodePort
  ports:
    - name: http-web
      port: {{ .Values.port.graphstudio.httpPort }}
  selector:
    app: nebula-graph-studio
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nebula-nginx
  name: nebula-nginx
  namespace: {{ .Values.namespace }}
spec:
  publishNotReadyAddresses: true
  type: NodePort
  ports:
    - name: http-nginx
      port: {{ .Values.port.nginx.httpPort }}
  selector:
    app: nebula-graph-studio-nginx
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nebula-http-gateway
  name: nebula-http-gateway
  namespace: {{ .Values.namespace }}
spec:
  publishNotReadyAddresses: true
  type: NodePort
  ports:
    - name: http-gateway
      port: {{ .Values.port.httpgateway.httpPort }}
  selector:
    app: nebula-http-gateway
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nebula-graph-importer
  name: nebula-graph-importer
  namespace: {{ .Values.namespace }}
spec:
  publishNotReadyAddresses: true
  type: NodePort
  ports:
    - name: tcp
      port: {{ .Values.port.importer.tcpPort }}
  selector:
    app: nebula-graph-importer
---