apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nebula-storaged
  labels:
    app: nebula-storaged
spec:
  selector:
    matchLabels:
      app: nebula-storaged
  maxUnavailable: 1
