kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /etc/localtime
        containerPath: /etc/localtime
  - role: worker
    extraMounts:
      - hostPath: /etc/localtime
        containerPath: /etc/localtime
  - role: worker
    extraMounts:
      - hostPath: /etc/localtime
        containerPath: /etc/localtime
  - role: worker
    extraMounts:
      - hostPath: /etc/localtime
        containerPath: /etc/localtime
  - role: worker
    extraMounts:
      - hostPath: /etc/localtime
        containerPath: /etc/localtime