# specify kubernetes namespace
namespace: default

# the nebula images
image:
  # the nebula-graphd images, change tag to use a different version.
  graphd:
    repository: vesoft/nebula-graphd
    tag: v2.0.0-rc1
    pullPolicy: Always
  # the nebula-metad images, change tag to use a different version.
  metad:
    repository: vesoft/nebula-metad
    tag: v2.0.0-rc1
    pullPolicy: Always
  # the nebula storaged images, change tag to use a different version.
  storaged:
    repository: vesoft/nebula-storaged
    tag: v2.0.0-rc1
    pullPolicy: Always
  # the nebula graph-studio images, change tag to use a different version.
  graphstudio:
    repository: vesoft/nebula-graph-studio
    tag: v2
    pullPolicy: Always
  # the nebula http-gateway images, change tag to use a different version.
  httpgateway:
    repository: vesoft/nebula-http-gateway
    tag: v2
    pullPolicy: Always
  # the nginx images for nebula graph-studio, change tag to use a different version.
  nginx:
    repository: nginx
    tag: alpine
    pullPolicy: Always

# set livenessProbe, kubelet will check nebula pod alive
livenessProbe:
  graphd:
    Enable: true
  metad:
    Enable: true
  storaged:
    Enable: true
  graphstudio:
    Enable: true
  nginx:
    Enable: true
  httpgateway:
    Enable: true

## Optional resource requests and limits for the nebula container
resources:
  graphd:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 1000m
      memory: 1024Mi

  metad:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 1000m
      memory: 1024Mi

  storaged:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 1000m
      memory: 1024Mi

  graphstudio:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 1000m
      memory: 512Mi

  nginx:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 1000m
      memory: 512Mi

  httpgateway:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 1000m
      memory: 512Mi

replication:
  ## Number of nebula-storaged replicas
  storaged:
    replicas: 3
  ## Number of nebula-metad replicas
  metad:
    replicas: 3
  ## Number of nebula-graphd replicas
  graphd:
    replicas: 3
  ## Number of nebula-graph-studio replicas
  graphstudio:
    replicas: 1
  ## Number of nginx replicas for nebula-graph-studio
  nginx:
    replicas: 1
  ## Number of http-gateway replicas for nebula-graph-studio
  httpgateway:
    replicas: 1

port:
  ## Service And Container Port Setting of Nebula-Graphd
  graphd:
    serviceType: ClusterIP
    thriftPort: 3699
    httpPort: 13000
    http2Port: 13002
  ## Service And Container Port Setting of Nebula-Storaged
  storaged:
    serviceType: ClusterIP
    thriftPort: 45600
    raftPort: 45601
    httpPort: 12000
    http2Port: 12002
  ## Service And Container Port Setting of Nebula-Metad
  metad:
    serviceType: ClusterIP
    thriftPort: 44500
    raftPort: 44501
    httpPort: 11000
    http2Port: 11002
  ## Service And Container Port Setting of Nebula-Graph-Studio
  graphstudio:
    serviceType: ClusterIP
    httpPort: 7001
  ## Service And Container Port Setting of Nebula-Graph-Studio's Nginx
  nginx:
    serviceType: ClusterIP
    httpPort: 7001
  ## Service And Container Port Setting of Nebula's Http-Gateway
  httpgateway:
    serviceType: ClusterIP
    httpPort: 8080

## Storage Setting of Nebula-Metad and Nebula-Storaged
storage:
  storageClass: ssd
  storaged:
    size: 20Gi
  metad:
    size: 20Gi

nodeSelector:
  nebula: "yes"

tolerations: []

affinity: {}
